language: ruby

rvm:
  - 2.4

services:
  - postgresql

before_script:
  - psql -c 'create database task_api_test;' -U postgres

stages:
  - lint
  - test

jobs:
  include:
    - stage: lint
      script:
        - bundle exec rubocop

    - stage: test
      script:
        - bundle exec rake db:migrate
        - bundle exec rake db:setup
        - bundle exec rake spec

cache: bundler
