default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: task_api_dev

test:
  <<: *default
  database: task_api_test

production:
  <<: *default
  database: task_api_prod
  username: task_apio
  password: <%= ENV['TASK_API_DATABASE_PASSWORD']
